#!/usr/bin/env sh
#              _           _
#             | |         (_)
#  _   _  __ _| |__   __ _ _ _ __ ___
# | | | |/ _` | '_ \ / _` | | '__/ __|
# | |_| | (_| | |_) | (_| | | | | (__
#  \__, |\__,_|_.__/ \__,_|_|_|  \___|
#   __/ |
#  |___/

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# General space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# Space labels
yabai -m space 1 --label "Terminal"
yabai -m space 2 --label "Code"
yabai -m space 3 --label "Browser"
yabai -m space 4 --label "Tools"
yabai -m space 5 --label "Writer"
yabai -m space 6 --label "Media"
yabai -m space 7 --label "Float"

# Space config
yabai -m config --space 6 layout float
yabai -m config --space 7 layout float

# Global settings
yabai -m config status_bar                   on
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_border                off
# yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config external_bar all:26:0

# Float preferences
yabai -m rule --add app="^System Preferences$" sticky=on manage=off
yabai -m rule --add app="^系统偏好设置$" sticky=on manage=off
yabai -m rule --add app="^Finder$" sticky=on manage=off
yabai -m rule --add app="^访达$" sticky=on manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on manage=off
yabai -m rule --add app="^磁盘工具$" sticky=on manage=off
yabai -m rule --add app="^System Information$" sticky=on manage=off
yabai -m rule --add app="^系统信息$" sticky=on manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on manage=off
yabai -m rule --add app="^活动监视器$" sticky=on manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^信息$" manage=off
yabai -m rule --add app="^FaceTime" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^日历$" manage=off
yabai -m rule --add app="^提醒事项$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^预览$" manage=off
yabai -m rule --add app="^DeepL$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Happy Hacking Keyboard Keymap Tool$" manage=off
yabai -m rule --add app="微信" sticky=on layer=above manage=off
yabai -m rule --add app="Telegram" sticky=on layer=above manage=off
yabai -m rule --add app="QQ" sticky=on layer=above manage=off
yabai -m rule --add app="钉钉" sticky=on layer=above manage=off

# Space rule
yabai -m rule --add label="Terminal" app="kitty" space=1
yabai -m rule --add label="Terminal" app="Alacritty" space=1

yabai -m rule --add label="Code" app="Emacs" space=2

yabai -m rule --add label="Browser" app="^Safari$" space=3
yabai -m rule --add label="Browser" app="^Google Chrome$" space=3

yabai -m rule --add label="Tools" app="MySQL" space=4
yabai -m rule --add label="Tools" app="DBeaver" space=4
yabai -m rule --add label="Tools" app="^Another Redis DeskTop Manager$" space=4

yabai -m rule --add label="Writer" app="WPS" space=5
yabai -m rule --add label="Writer" app="StarUML" space=5

yabai -m rule --add label="Media" app="^Music$" space=6
yabai -m rule --add label="Media" app="^音乐$" space=6
yabai -m rule --add label="Media" app="网易云音乐" space=6
yabai -m rule --add label="Media" app="mpv" space=6
yabai -m rule --add label="Media" app="QuickTime Player" space=6
yabai -m rule --add label="Media" app="爱奇艺" space=6

echo "yabai configuration loaded.."
