# A TOML linter such as https://github.com/tombi-toml/tombi can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.

#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
ratio          = [ 1, 3, 4 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
sort_translit  = false
sort_fallback  = "alphabetical"
linemode       = "size_and_mtime"
show_hidden    = true
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll", "drag" ]

[preview]
wrap            = "yes"
tab_size        = 2
max_width       = 1200
max_height      = 1800
cache_dir       = "~/.cache/yazi"
image_delay     = 100
image_filter    = "triangle"
image_quality   = 75
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
extract = [
  { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
  { run = 'ouch d -y %*', desc = "Extract here with ouch", for = "windows" },
  { run = "ya pub extract --list %s", desc = "Extract here" },
]

[plugin]
prepend_fetchers = [
  { url = "*", run = "git", group = "git" },
  { url = "*/", run = "git", group = "git" }
]
prepend_preloaders = [
  # Replace magick, image, video with mediainfo
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },

  # Adobe Photoshop is image/adobe.photoshop, already handled above
  # Adobe Illustrator
  { mime = "application/postscript", run = "mediainfo" },
  { mime = "application/illustrator", run = "mediainfo" },
  { mime = "application/dvb.ait", run = "mediainfo" },
  { mime = "application/vnd.adobe.illustrator", run = "mediainfo" },
  { mime = "image/x-eps", run = "mediainfo" },
  { mime = "application/eps", run = "mediainfo" },

  # Sometimes AI file is recognized as "application/pdf". Lmao.
  # In this case use file extension instead:
  { url = "*.{ai,eps,ait}", run = "mediainfo" },
]
prepend_previewers = [
  # Replace magick, image, video with mediainfo
  { mime = "{audio,video,image}/*", run = "mediainfo"},
  { mime = "application/subrip", run = "mediainfo" },

  # Adobe Photoshop is image/adobe.photoshop, already handled above
  # Adobe Illustrator
  { mime = "application/postscript", run = "mediainfo" },
  { mime = "application/illustrator", run = "mediainfo" },
  { mime = "application/dvb.ait", run = "mediainfo" },
  { mime = "application/vnd.adobe.illustrator", run = "mediainfo" },
  { mime = "image/x-eps", run = "mediainfo" },
  { mime = "application/eps", run = "mediainfo" },

  # Sometimes AI file is recognized as "application/pdf". Lmao.
  # In this case use file extension instead:
  { url = "*.{ai,eps,ait}", run = "mediainfo" },

  # Archive previewer
  { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run = "ouch" },
  # Csv
  { url = "*.csv", run = 'piper -- bat -p --color=always "$1"'},
  # Markdown
  { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'},
  # Directory
  { url = "*/", run = 'piper -- lsd --tree --depth 3 --icon always --color always --group-directories-first "$1"' }
]
